## 3. Functions
### 함수가 여러 값을 반환할 때 4개 이상을 unpack하지 말 것
unpacking을 사용해 함수는 2개 이상의 값을 반환할 수 있다. 만약, 2개를 초과하는 값을 반환하거나, list를 반환하는 경우 별표 식을 사용한 unpacking도 가능하다.
하지만, 반환 값이 너무 많으면 값들의 순서를 혼동하기 쉽고, unpacking하는 코드가 길어져 가독성이 나빠진다는 문제가 있다.
따라서, 함수가 여러 값을 반환할 때 값이나 변수를 4개 이상 사용하는 것은 좋지 않다. 여러 값을 반환해야 하는 경우는 경량 클래스나 `namedtuple`을 사용하고, 이를 반환하게 하는 것이 좋다.
### `None`을 반환하는 대신 예외 발생시키기
함수가 None값을 반환하도록 하는 경우, 해당 함수가 반환한 값에 따라 처리를 할 수 있다. 하지만, 반환값이 `None`인지 확인하는 대신, 빈 값인지 확인하는 실수를 할 확률이 높아진다.
```python
def careful_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None

x, y = 0, 5
result = careful_divide(x, y)
if not result:  # None검사 대신 빈 값 검사. 올바른 나누기인데도 값이 0이므로 유효하지 않은 출력이라고 나옴.
    print('Invalid inputs')

>>>
Invalid inputs
```
이를 막기 위해 반환값을 2-tuple로 분리하여, 튜플의 첫 번째 값은 연산의 성공 여부를, 두 번째 값은 연산 성공 시 계산 값을 담는다. 해당 함수를 호출하는 쪽은 튜플을 unpacking하고, 성공 여부를 확인해야 한다. 이 방법의 문제점은 튜플의 첫 번째 값을 `_`을 이용해 쉽게 무시하기 쉽다는 것이다.
```python
def careful_divide(a, b):
    try:
        return True, a / b
    except ZeroDivisionError:
        return False, None

# _, result = careful_divide(x, y)  # ???
success, result = careful_divide(x, y)
if not success:
    print('Invalid inputs')
```
  
또 다른 방법은, `None`을 반환하지 않는 대신, 예외를 발생시켜 호출자가 처리하도록 하는 것이다. 이 방법은 함수를 호출하는 쪽에서 더 이상 조건문을 사용해 값이 올바른 지 확인하지 않아도 되고, `try`문의 `else`에서 값을 바로 사용할 수 있다.
이러한 방식을 사용하게 되면, type annotation을 이용해 해당 함수가 `float`와 같은 형을 반환하고, `None`이 절대 반환되지 않음을 알릴 수 있다. 또한, 함수에서 어떤 예외가 발생할 수 있는지를 나타내야 하므로 docstring을 이용해 명시해야 한다.
```python
def careful_divide(a: float, b: float) -> float:
    """Divides a by b.
    Raises:
    ValueError: When the inputs cannot be divided.
    """
    try:
        return a / b
    except ZeroDivisionError as e:
        raise ValueError('Invalid inputs')
```
### 클로저가 변수의 범위와 어떻게 상호작용하는지 확인하기
숫자로 이루어진 list를 정렬할 때, 앞쪽에는 우선순위를 부여한 몇몇 숫자를 위치시켜야 한다고 가정한다. 이는 보통 list의 `sort`에 `key`의 인자로 helper function을 전달하는 것으로 구현한다.
```python
def sort_priority(values, group):
    def helper(x):
        if x in group:
            return (0, x)
        return (1, x)
    values.sort(key=helper)

numbers = [8, 3, 1, 2, 5, 4, 7, 6]
group = {2, 3, 5, 7}
sort_priority(numbers, group)
print(numbers)

>>>
[2, 3, 5, 7, 1, 4, 6, 8]
```
python이 클로저(자신의 정의된 영역 밖의 변수를 참조하는 함수)를 지원하므로 `sort_priority`가 `group`에 접근할 수 있다. 또한, python에서 함수는 first-class object(직접 가리킬 수 있고, 변수에 대입하거나 다른 함수의 인자로 전달할 수 있고, 비교 및 반환이 가능한 객체)이므로 `sort`는 클로저 함수를 `key`인자로 받을 수 있다. 
  
위의 함수를 수정해, 우선순위가 높은 원소가 있는지에 대한 여부도 반환한다면 다음과 같이 수정할 수 있을 것이다.
```python
def sort_priority2(numbers, group):
    found = False
    def helper(x):
        if x in group:
            found = True    # 간단해 보임
            return (0, x)
        return (1, x)
    numbers.sort(key=helper)
    return found

found = sort_priority2(numbers, group)
print('Found:', found)
print(numbers)

>>>
Found: False
[2, 3, 5, 7, 1, 4, 6, 8]
```
정렬은 정상적으로 되지만, 우선순위가 있는 원소가 있음에도 Found의 결과는 `False`이다.  
식 안에서 변수를 참조할 때, 인터프리터는 다음 순서대로 영역을 뒤진다.
1. 현재 함수의 영역
2. 현재 함수를 둘러싼 영역
3. 현재 코드가 들어 있는 모듈 영역(또는 global scope)
4. 내장 영역(built-in scope. `len`, `str`등의 함수가 있는 영역)

위의 영역에도 변수가 없다면 `NameError`예외가 발생한다.
  
변수에 값 대입 시에는, 해당 변수가 동일 영역에 있다면 그 변수의 값만 바꾸고, 영역에서 정의되어있지 않다면 새로운 변수를 만드는 변수 정의로 취급된다.
즉, 위의 코드에서 `helper`내부의 `found = True`는 `helper`영역에서 새로운 변수를 정의하는 것으로 취급되고, 외부의 기존 변수에 대입하는 것으로 취급되지 않는다.
이러한 문제를 scoping bug라고 부른다.
Python에는 클로저 밖으로 데이터를 끌어내기 위해 `nonlocal`을 사용한다. `nonlocal`을 붙이면 위의 영역 결정 규칙에 따라 대입될 변수가 결정된다. 단, 모듈 수준 영역까지 찾아 올라가지는 않는다.

```python
def sort_priority3(numbers, group):
    found = False
    def helper(x):
        nonlocal found # Added
        if x in group:
            found = True
            return (0, x)
        return (1, x)
    numbers.sort(key=helper)
    return found
```
`nonlocal`은 대입할 데이터가 클로저 밖에 있다는 것을 알려준다. 또한, 모듈 영역을 사옹해야 한다고 지정하는 `global`문을 보완해준다.
하지만, 간단한 함수가 아닌 경우에는 `nonlocal`을 사용하지 말아야 한다.
`nonlocal`을 사용하지 않고, 도우미 함수로 상태를 감쌀 수도 있다.
```python
class Sorter:
    def __init__(self, group):
        self.group = group
        self.found = False

    def __call__(self, x):
    if x in self.group:
        self.found = True
        return (0, x)
    return (1, x)

sorter = Sorter(group)
numbers.sort(key=sorter)
assert sorter.found is True
```
### 변수 위치 인자(positional argument)를 사용해 시각적 잡음 줄이기
위치 인자(가변 인자, 스타 인자)를 사용하면 함수 호출이 깔끔해지고 시각적 잡음이 줄어든다. 어떤 함수가 메세지와 list를 인자로 받을 때, 함수가 고정된 인자 수를 가지면 list가 필요 없을 때도 빈 list를 넘겨아 한다. list가 필요 없을 때 생략하면 좋으므로, 마지막 위치 인자 이름 앞에 `*`를 붙이면 해당 인자는 필수가 아니게 된다. 또한, 가변 인자를 사용해도 함수 본문은 바뀌지 않는다.
```python
def log(message, *values):
    if not values:
        print(message)
    else:
        values_str = ', '.join(str(x) for x in values)
        print(f'{message}: {values_str}')
log('My numbers are', 1, 2)
log('Hi there')
# *values 대신 values를 사용한다면
# log('My numbers are', [1, 2])
# log('Hi there', [])

>>>
My numbers are: 1, 2
Hi there
```
sequence를 가변 인자 함수에 넘길 때도 `*`를 사용한다.
```python
favorites = [7, 33, 99]
log('Favorite colors', *favorites)

>>>
Favorite colors: 7, 33, 99
```
단, 위치 인자가 함수에 전달되기 전에 항상 튜플로 변환되므로, 함수 호출 측에서 generator 앞에 `*`를 붙이면 generator의 모든 원소를 얻기 위해 반복하게 된다. 이때 만들어지는 튜플은 generator가 만든 모든 값을 포함하므로 메모리를 많이 소비하거나 프로그램이 중단될 수 있다.
따라서, `*args`는 가변 인자 부분에 들어가는 인자의 개수가 충분히 작다는 것을 이미 알고 있을 때 사용하는 게 좋다. 보통 여러 literal이나 변수 이름을 함께 전달하는 함수 호출에 이상적이고, 프로그래머의 편의와 가독성을 위한 기능이다.
또한, 함수에 새로운 위치 인자를 추가하면 해당 함수를 호출하는 모든 코드를 수정해야 한다.
```python
def log(sequence, message, *values):
    if not values:
        print(f'{sequence} - {message}')
    else:
        values_str = ', '.join(str(x) for x in values)
        print(f'{sequence} - {message}: {values_str}')

log(1, 'Favorites', 7, 33)
log(1, 'Hi there')
log('Favorite numbers', 7, 33) # 이전처럼 호출하면 잘못된 출력이 나옴.
>>>
1 - Favorites: 7, 33
1 - Hi there
Favorite numbers - 7: 33
```
잘못된 동작을 함에도 예외나 발생하지 않을 수 있으므로 버그를 추적하기 힘들다. 이를 막기 위해 `*args`형태를 받아들이는 함수를 확장할 때는 키워드 기반 인자만 사용하거나, type annotation을 사용해야 한다.
### 키워드 인자로 선택적 기능 제공하기
Python의 함수에서는 모든 일반적인 인자를 키워드를 사용해 넘길 수 있다. 위치 기반 인자가 모두 제공된다면 키워드 인자의 순서는 상관없다. 위치 기반 인자는 키워드 인자보다 앞에 지정해야 한다.
```python
remainder(20, 7)
remainder(20, divisor=7)
remainder(number=20, divisor=7)
remainder(divisor=7, number=20)

# remainder(20, number=7) # error
```
dictionary의 내용물을 사용해 인자를 넘겨줄 때는 `**`을 사용할 수 있고, 위치 인자나 키워드 인자와 섞어서 호출할 수 있다. 단, 중복되는 인자가 있으면 안된다. 또한, 여러 개의 `**`을 사용할 수 있고, 이들 간 겹치는 키가 없어야 한다.
```python
my_kwargs = {
    'divisor': 7,
}
assert remainder(number=20, **my_kwargs) == 6
```
아무 키워드 인자나 받으려면, `**kwargs`파라미터를 사용한다. 함수 본문에서 해당 dictionary를 이용해 필요한 처리를 할 수 있다.
```python
def print_parameters(**kwargs):
    for key, value in kwargs.items():
        print(f'{key} = {value}')

print_parameters(alpha=1.5, beta=9, gamma=4)
```
키워드 인자를 사용하면 코드를 처음 보는 사람들에게 함수 호출의 의미를 알려줄 수 있다. 
또한, 함수 정의에서 default값을 지정할 수 있다. default값을 지정하면 해당 인자를 반드시 넘겨주지 않아도 기본값이 들어가므로 시각적 잡음을 줄일 수 있다. 
또한, 어떤 함수를 사용하던 기존 호출자에게 하위 호환성을 제공하면서 함수 파라미터를 확장하는 방법을 제공한다. 즉, 함수에 새로운 선택적인 파라미터를 추가해도 호출하는 쪽에서의 코드는 변하지 않는다는 의미이다.
  
단, 선택적인 키워드 인자도 위치 인자로 지정할 수 있으므로, `flow_rate(weight_diff, time_diff, 3600, 2.2)`와 같이 사용한다면 혼동을 야기할 수 있다. 따라서, 선택적인 인자 사용 시 항상 키워드 인자를 사용하는 것이 좋다.
### 동적인 default 인자를 지정하기 위해 `None`과 docstring 사용
default인자는 정적으로 정해진다. 즉, `def log(message, when=datetime.now())`와 같이 정의된 함수가 있다면 함수를 호출할 때 마다 when이 결정되는 것이 아닌, 함수 정의 시점에서 한 번만 호출되므로 계속 같은 값만 나온다. 이러한 경우, 주로 default 값을 `None`으로 지정한 뒤, 실제 동작을 docstring에서 문서화한다.
```python
def log(message, when=None):
    """Log a message with a timestamp.

    Args:
        message: Message to print.
        when: datetime of when the message occurred.
            Defaults to the present time.
    """
    if when is None:
        when = datetime.now()
    print(f'{when}: {message}')

log('Hi there!')
sleep(0.1)
log('Hello again!')
>>>
2019-07-06 14:06:15.222419: Hi there!
2019-07-06 14:06:15.322555: Hello again!
```
또한, 다음과 같은 코드의 경우, default에 지정된 dictionary가 `decode`호출에 모두 공유되므로, 서로 다른 dictionary가 출력되는 것이 아닌, 같은 값이 출력된다.
```python
def decode(data, default={}):
    try:
        return json.loads(data)
    except ValueError:
        return default

foo = decode('bad data')
foo['stuff'] = 5
bar = decode('also bad')
bar['meep'] = 1
print('Foo:', foo)
print('Bar:', bar)

assert foo is bar

>>>
Foo: {'stuff': 5, 'meep': 1}
Bar: {'stuff': 5, 'meep': 1}
```
이 역시 `default=None`으로 만들고 docstring에 동작 방식을 기술하면 된다.
### 키워드 인자만 사용하거나 위치 인자만 사용하여 명확성 강제
키워드 인자를 사용하지 않으면 함수 호출 시 변수의 위치가 혼동되기 쉽다. 따라서, 인자의 기본값을 설정하고 키워드 인자를 넘겨주는 방식이 좋다.
하지만, 이러한 방식의 키워드 인자는 선택적인 상황이므로, 호출자가 키워드만 사용하는 인자를 통해 의도를 명확히 밝히는 것이 좋다.
인자 목록에 `*`를 추가하면, 위치 인자의 마지막과 키워드만 사용하는 인자의 시작을 구분해주므로, 키워드 인자 사용을 강제할 수 있다.
```python
def safe_division_c(number, divisor, *,
                    ignore_overflow=False,
                    ignore_zero_division=False):
    ...

safe_division_c(1.0, 10**500, True, False)
>>>
Traceback ...
TypeError: safe_division_c() takes 2 positional arguments but 4 were given
```
```python
result = safe_division_c(1.0, 0, ignore_zero_division=True)
assert result == float('inf')
```
단, 이러한 경우에도 호출하는 쪽에서 위치 인자를 넘겨줄 때 키워드 인자로 넘겨줄 수도 있게 되고, 그렇다면 인자 이름이 변경되는 경우 등에 의해 오류가 발생할 수 있다.
```python
# 아래와 같이 호출했을 때,
assert safe_division_c(number=2, divisor=5) == 0.4
assert safe_division_c(divisor=5, number=2) == 0.4

# number, divisor가 각각 numerator와 denominator라는 이름으로 바뀌면 위의 호출에서 오류 발생
def safe_division_c(numerator, denominator, *,
                    ignore_overflow=False,
                    ignore_zero_division=False):
    ...
```
python 3.8에서는 위치로만 지정하는 인자를 지정할 수 있고, 지정 시 키워드 인자로는 사용할 수 없다. `/`기호를 사용해 위치로만 지정하는 인자의 끝을 표시한다.
```python
def safe_division_d(numerator, denominator, /, *,
                    ignore_overflow=False,
                    ignore_zero_division=False):
    ...

safe_division_d(numerator=2, denominator=5)

>>>
Traceback ...
TypeError: safe_division_d() got some positional-only arguments passed as keyword arguments: 'numerator, denominator'
```
`/`와 `*`사이에 있는 파라미터는 위치 인자 및 키워드 인자 모두 사용할 수 있다.
### `functools.wraps`를 사용해 함수 데코레이터 정의
데코레이터는 감싸고 있는 함수가 호출되기 전과 후에 코드를 추가로 실행해준다. 즉, 함수의 입력 인자, 반환 값, 함수에서 발생한 오류에 접근할 수 있다는 뜻이다.
만약, 함수가 호출될 때 마다 인자 값과 반환 값을 출력하려면, 다음과 같이 정의 및 사용할 수 있다.
```python
def trace(func):
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)
        print(f'{func.__name__}({args!r}, {kwargs!r}) '
              f'-> {result!r}')
        return result
    return wrapper

@trace
def fibonacci(n):
    """Return the n-th Fibonacci number"""
    if n in (0, 1):
        return n
    return (fibonacci(n - 2) + fibonacci(n - 1))

fibonacci(4)
>>>
fibonacci((0,), {}) -> 0
fibonacci((1,), {}) -> 1
fibonacci((2,), {}) -> 1
fibonacci((1,), {}) -> 1
fibonacci((0,), {}) -> 0
fibonacci((1,), {}) -> 1
fibonacci((2,), {}) -> 1
fibonacci((3,), {}) -> 2
fibonacci((4,), {}) -> 3
```
> 위의 기능은 함수 호출이 재귀적으로 중첩된 경우를 디버깅할 때 유용하다.

데코레이터를 사용한 것은, 해당 함수에 대해 데코레이터를 호출한 뒤 그 결과를 동일 영역 내에 같은 이름으로 다시 등록하는 것과 같다.
```python
fibonacci = trace(fibonacci)
```
이렇게 나온 fibonacci는 `wrapper`의 코드를 원래 fibonacci를 실행하기 전과 후에 실행한다.
단, 이렇게 사용하면 데코레이터가 반환하는 함수의 이름이 fibonacci가 아니게 되는 문제가 있다. `trace`는 `wrapper`를 반환하는데, 이 `wrapper`함수가 모듈에 fibonacci라는 이름으로 등록이 되기 때문이다. 이는 디버거와 같이 introspection(실행 시점에 프로그램이 어떻게 실행되는지 관찰하는 것)을 하는 도구에서 문제가 된다.
예를 들어, `help(fibonacci)`를 호출하면 원래라면 docstring이 출력되어야 하지만, 데코레이터가 감싸고 있는 원래 함수의 위치를 찾을 수 없기 때문에 출력되지 않는다.
이를 해결하기 위해, `functools`내에 정의된 `wraps`도우미 함수를 이용할 수 있다.
```python
from functools import wraps

def trace(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        ...
    return wrapper

@trace
def fibonacci(n):
    ...
```
help()의 정상 작동 외에도, `pickle`객체 직렬화와 표준 attribute(`__name__`, `__module__`등)들도 보존이 된다.